"""Canonical ARC solver for puzzle bd5af378.

Structure of every input: a background-colored rectangle bordered on exactly one
full row (top or bottom) and one full column (left or right) by a single "line"
color. Those two full segments meet at an L-corner.

Re-expressed in a canonical frame where the corner sits at the top-left (0,0),
the output is generated by a fixed nested-L / diagonal rule:

    (0,0)            -> 8
    row 0 (c>=1)     -> background
    col 0 (r>=1)     -> background
    (1,1)            -> 8
    row 1 (c>=2)     -> line color
    col 1 (r>=2)     -> line color
    interior r,c>=2  -> background on the main diagonal (r==c), else 8

`infer_T` builds the explicit latent mask {(r,c): color} directly in the original
frame; `apply_T` copies the input and overwrites only the masked cells.
"""


def _find_corner(grid):
    """Return (full_row_index, full_col_index, line_color, bg_color)."""
    H, W = len(grid), len(grid[0])
    full_rows = [r for r in range(H) if len(set(grid[r])) == 1]
    full_cols = [c for c in range(W)
                 if len(set(grid[r][c] for r in range(H))) == 1]
    fr = full_rows[0]
    fc = full_cols[0]
    line = grid[fr][0]
    counts = {}
    for row in grid:
        for v in row:
            counts[v] = counts.get(v, 0) + 1
    bg = max(counts, key=counts.get)
    return fr, fc, line, bg


def infer_T(input_grid):
    H, W = len(input_grid), len(input_grid[0])
    fr, fc, line, bg = _find_corner(input_grid)

    # Direction vectors pointing from the corner into the interior block.
    dr = 1 if fr == 0 else -1
    dc = 1 if fc == 0 else -1

    # Number of canonical rows / cols available from the corner.
    nrows = H  # corner row plus interior rows fill the whole height
    ncols = W

    def orig(ci, cj):
        return (fr + ci * dr, fc + cj * dc)

    T = {}

    def put(ci, cj, color):
        r, c = orig(ci, cj)
        if 0 <= r < H and 0 <= c < W:
            T[(r, c)] = color

    # Canonical frame construction.
    for ci in range(nrows):
        for cj in range(ncols):
            if ci == 0 and cj == 0:
                color = 8
            elif ci == 0 or cj == 0:
                color = bg
            elif ci == 1 and cj == 1:
                color = 8
            elif ci == 1 or cj == 1:
                color = line
            else:
                # interior (ci>=2, cj>=2): diagonal of background, else 8
                color = bg if ci == cj else 8
            put(ci, cj, color)

    return T


def apply_T(input_grid, T):
    out = [row[:] for row in input_grid]
    for (r, c), color in T.items():
        out[r][c] = color
    return out


def solve(input_grid):
    T = infer_T(input_grid)
    return apply_T(input_grid, T)
